export const consultingProfile = {
  name: "Kannan Sriniyappan Balakrishnan",
  role: "Senior IAM Technical Consultant · SailPoint Ambassador · CyberArk Integration Specialist",
  location: "Frankfurt, Hesse, Germany",
  siteName: "myIAM",
  siteCaption: "Enrich Your Innovation & Elevate Your Identity",
  brandLogoUrl: "/manus-storage/myIAM-ISC_fc87f9d9.png",
  ambassadorBadgeUrl: "/manus-storage/sailpoint-ambassador_dfce06e0.png",
  ambassadorBadgeDescription: "A SailPoint Developer Community recognition for contributing technical knowledge and peer learning. It signals active community participation; it is not a product certification.",
  linkedinUrl: "https://www.linkedin.com/in/kannan-iam-specialist/",
  calendlyUrl: "https://calendly.com/sbkannan/30min",
  directInquiryEmail: "sbkannan@hotmail.com",
  focusAreas: ["SailPoint IdentityIQ", "Identity governance architecture", "Entra ID & CyberArk integrations"],
  consultationThemes: [
    { title: "Identity governance architecture", description: "Clarify authoritative sources, identity correlation, ownership models, and the control boundaries that give an IGA program a dependable foundation." },
    { title: "SailPoint delivery patterns", description: "Work through IdentityIQ configuration, workflow design, rule delivery, and environment promotion choices before they become operational constraints." },
    { title: "Access governance and lifecycle", description: "Shape joiner, mover, leaver, certification, and entitlement models around accountable decisions rather than manual exception handling." },
    { title: "Integration and trust design", description: "Assess Entra ID, CyberArk, OAuth, connector, and certificate-trust decisions that affect provisioning reliability and audit evidence." },
  ],
  caseStudies: [
    {
      id: "01",
      type: "Public architecture insight",
      title: "Multi-source IGA architecture",
      summary: "A reference context for aligning multiple identity sources, correlation logic, and governance decisions in a single IGA operating model.",
      categories: ["IGA Architecture", "Identity Data Governance"],
      focus: ["Source authority", "Identity correlation", "IGA architecture"],
      href: "https://www.linkedin.com/pulse/multi-source-identity-governance-administration-iga-kannan-5dzme",
    },
    {
      id: "02",
      type: "Integration reference",
      title: "Entra ID × SailPoint IdentityIQ",
      summary: "A practical integration context covering OAuth 2.0, application registration, aggregation and provisioning, plus certificate trust boundaries.",
      categories: ["SailPoint IdentityIQ", "Microsoft Entra ID"],
      focus: ["OAuth 2.0", "Provisioning", "Certificate trust"],
      href: "https://www.linkedin.com/posts/kannan-iam-specialist_activity-7495529822409035777-cEqg",
    },
    {
      id: "03",
      type: "Implementation case study",
      title: "SailPoint IdentityIQ governed delivery blueprint",
      summary: "An anonymized, on-site reference case for structuring IdentityIQ delivery around lifecycle accountability, controlled releases, and verifiable access governance.",
      categories: ["SailPoint IdentityIQ", "Release Engineering", "Access Governance"],
      focus: ["JML lifecycle", "Workflow design", "Release controls"],
      href: "/blog/sailpoint-identityiq-governed-implementation-case-study",
    },
    {
      id: "04",
      type: "Reference delivery scenario",
      title: "Privileged access governance control design",
      summary: "A non-client reference scenario for mapping privileged roles, approval boundaries, vault integration touchpoints, and review evidence before an access-control rollout.",
      categories: ["Access Governance", "CyberArk Integration"],
      focus: ["Privileged roles", "Approval evidence", "Vault touchpoints"],
      href: "",
    },
    {
      id: "05",
      type: "Reference delivery scenario",
      title: "Lifecycle data quality and correlation pattern",
      summary: "A non-client reference scenario for defining source authority, correlation exceptions, and operational reconciliation signals across complex joiner, mover, and leaver data.",
      categories: ["Identity Data Governance", "Identity Lifecycle Management"],
      focus: ["Source authority", "Correlation exceptions", "Reconciliation"],
      href: "",
    },
    {
      id: "06",
      type: "Reference delivery scenario",
      title: "Cloud application onboarding guardrails",
      summary: "A non-client reference scenario for establishing application onboarding criteria, entitlement ownership, provisioning checkpoints, and release evidence for a new cloud-connected service.",
      categories: ["Lifecycle Provisioning", "Release Engineering"],
      focus: ["Entitlement ownership", "Provisioning checks", "Release evidence"],
      href: "",
    },
  ],
  linkedInFeed: [
    {
      slug: "multi-source-identity-governance-architecture",
      kind: "LinkedIn article",
      date: "April 2026",
      publishedAt: "2026-04-09T00:00:00.000Z",
      author: "Kannan Sriniyappan Balakrishnan",
      title: "Multi-Source Identity Governance and Administration (IGA): Concepts, Architecture and Difference",
      excerpt: "An overview of how a modern IGA platform can ingest, correlate, and govern identity data from multiple sources.",
      href: "https://www.linkedin.com/pulse/multi-source-identity-governance-administration-iga-kannan-5dzme",
      sourceLabel: "Original LinkedIn article",
      readingTime: "6 min read",
      category: "IGA Architecture",
      categories: ["IGA Architecture", "Identity Data Governance", "Identity Correlation"],
      tags: ["Authoritative sources", "Identity correlation", "Governance evidence"],
      sections: [
        { heading: "The problem is not simply another source", paragraphs: ["Multi-source governance begins when identity data stops being cleanly singular. HR, contractor management, directories, business applications, and acquired environments can all describe the same person differently. Treating each source as equally authoritative produces duplicate identities, ambiguous ownership, and access decisions that cannot be explained.", "The architecture question is therefore not how many connectors can be configured. It is which source is trusted for each identity fact, how conflicts are resolved, and how an identity remains coherent when one source changes before another."] },
        { heading: "Design around authority, correlation, and evidence", paragraphs: ["A durable model makes authority explicit. Define the system of record for each attribute, document the circumstances in which an exception is accepted, and avoid letting the last successful aggregation silently become policy. This protects lifecycle and access decisions from accidental data precedence.", "Correlation should be deterministic where possible, with governed fallbacks for incomplete identifiers or verified exceptions. Each merge, non-match, and manual decision should leave enough evidence for operators to understand why an identity was linked or kept separate."] },
        { heading: "Turn the model into delivery checkpoints", paragraphs: ["Before production promotion, test the model with the difficult cases: rehires, contractors converting to employees, duplicate records, name changes, and source outages. These scenarios expose whether the design is truly an identity model or only a happy-path integration.", "Finally, make reconciliation operational. Monitor unmatched accounts, attribute conflicts, stale feeds, and manual correlation decisions. Governance improves when these signals are treated as a continuous control surface rather than a one-time migration activity."] },
      ],
      takeaways: ["Assign authority per identity attribute, not per platform.", "Make correlation decisions reviewable and reversible.", "Treat reconciliation metrics as operational governance evidence."],
    },
    {
      slug: "entra-id-sailpoint-iiq-integration-overview",
      kind: "LinkedIn architecture post",
      date: "August 2026",
      publishedAt: "2026-08-18T17:19:29.000Z",
      author: "Kannan Sriniyappan Balakrishnan",
      title: "IAM Integration Overview — Entra ID × SailPoint IIQ",
      excerpt: "An integration perspective on trust, OAuth 2.0, lifecycle automation, and compliance-aware identity governance.",
      href: "https://www.linkedin.com/posts/kannan-iam-specialist_activity-7495529822409035777-cEqg",
      sourceLabel: "Original LinkedIn post",
      readingTime: "5 min read",
      category: "SailPoint Integration",
      categories: ["SailPoint IdentityIQ", "Microsoft Entra ID", "Lifecycle Provisioning"],
      tags: ["OAuth 2.0", "Certificate trust", "Lifecycle provisioning"],
      sections: [
        { heading: "Start with the trust boundary", paragraphs: ["An Entra ID and SailPoint IdentityIQ integration is not just an endpoint configuration. It is a trust relationship that determines which system can read, create, change, or revoke access and how those actions are authenticated.", "Establish the application registration, OAuth 2.0 permissions, certificate or secret lifecycle, and least-privilege scope before beginning aggregation or provisioning work. The integration becomes easier to operate when the trust model is visible to both identity and platform teams."] },
        { heading: "Separate aggregation from provisioning intent", paragraphs: ["Aggregation gives IdentityIQ the evidence it needs to govern existing accounts and entitlements. Provisioning applies an approved lifecycle or access decision back into the target. Treating these as separate flows helps teams define ownership, test failures, and set realistic schedules.", "Each flow should have a clear error path. Failed aggregation should be observable without silently changing identity state; failed provisioning should retain enough request context to support retries, remediation, and audit explanation."] },
        { heading: "Build repeatability into delivery", paragraphs: ["Use a repeatable connector configuration, approved permission model, and test dataset before expanding to production users. Verify joiner, mover, leaver, and exception scenarios, not just initial connectivity.", "The result is an integration that supports governance rather than merely synchronizing accounts: decisions are attributable, operational failures are visible, and access changes can be traced through the lifecycle that initiated them."] },
      ],
      takeaways: ["Define OAuth permissions and credential ownership before connector testing.", "Keep aggregation evidence distinct from provisioning execution.", "Test lifecycle and failure scenarios alongside nominal connectivity."],
    },
    {
      slug: "sailpoint-identityiq-governed-implementation-case-study",
      kind: "Implementation case study",
      date: "August 2026",
      publishedAt: "2026-08-20T00:00:00.000Z",
      author: "Kannan Sriniyappan Balakrishnan",
      title: "SailPoint IdentityIQ implementation case study: A governed delivery blueprint",
      excerpt: "An anonymized reference case for structuring a SailPoint IdentityIQ implementation around lifecycle accountability, controlled delivery, and verifiable access governance.",
      href: "",
      sourceLabel: "On-site implementation case study",
      readingTime: "8 min read",
      category: "SailPoint Delivery",
      categories: ["SailPoint IdentityIQ", "Identity Lifecycle Management", "Access Governance", "Release Engineering"],
      tags: ["JML lifecycle", "Workflow design", "Release controls"],
      sections: [
        { heading: "Case context and scope", paragraphs: ["This anonymized reference case describes a governed SailPoint IdentityIQ implementation scenario rather than a named client engagement. The delivery objective is to bring joiner, mover, leaver activity, access-request workflow, and governance evidence into a consistent operating model.", "The implementation starts by clarifying what business event changes an identity, which source is authoritative, who approves access, and which team owns the exception path. These decisions prevent configuration from becoming a substitute for operating-model design."] },
        { heading: "Implementation approach", paragraphs: ["The delivery sequence begins with identity data mapping and lifecycle-state design, followed by account aggregation, entitlement modeling, and role or policy decisions. Workflow and rule design are promoted through controlled environments with documented test cases rather than edited directly in production.", "For access governance, the implementation defines certification populations, reviewer context, remediation ownership, and an audit trail that connects a decision back to the identity and entitlement evidence that supported it."] },
        { heading: "What successful delivery must demonstrate", paragraphs: ["A successful IdentityIQ implementation is not measured by connector count alone. It demonstrates that lifecycle events produce accountable changes, approval decisions are traceable, exceptions are visible, and deployment changes can be reproduced or rolled back safely.", "This reference case therefore uses operational evidence as the success standard: tested lifecycle scenarios, documented control ownership, release validation, and an observable remediation process. Client-specific outcomes or metrics should only be added after explicit approval."] },
      ],
      takeaways: ["Define lifecycle authority and exception ownership before workflow configuration.", "Promote IdentityIQ changes through tested, traceable release packages.", "Use governance evidence and remediation visibility as delivery success criteria."],
    },
  ],
} as const;
