import { ArrowLeft, ArrowUpRight, BookOpenText, CalendarDays, CheckCircle2, Clock3, ExternalLink, Linkedin, Share2, Sparkles, Tag } from "lucide-react";
import { Streamdown } from "streamdown";
import { useLocation, useRoute } from "wouter";
import ArticleReadingProgress from "@/components/ArticleReadingProgress";
import BlogTopicTagRssAction from "@/components/BlogTopicTagRssAction";
import { blogAuthorPath, blogPostsByTopic, blogTopicPath } from "@/lib/blogDiscovery";
import { consultingProfile } from "@/lib/consultingProfile";

export default function BlogPostDetail() {
  const [, params] = useRoute("/blog/:slug");
  const [, setLocation] = useLocation();
  const post = consultingProfile.linkedInFeed.find(item => item.slug === params?.slug);
  if (!post) return <div className="min-h-screen bg-background text-foreground"><main className="container py-24 text-center"><BookOpenText className="mx-auto h-8 w-8 text-accent" /><h1 className="mt-4 text-3xl">Article not found</h1><button onClick={() => setLocation("/blog")} className="mt-5 text-sm font-semibold text-primary">Return to the article library</button></main></div>;

  const relatedPosts = consultingProfile.linkedInFeed.filter(item => item.slug !== post.slug);
  const relatedTopics = Array.from(new Set([post.category, ...post.categories, ...post.tags])).map(topic => ({ topic, count: blogPostsByTopic(topic).filter(item => item.slug !== post.slug).length })).filter(item => item.count > 0).slice(0, 4);
  const shareUrl = typeof window === "undefined" ? "" : window.location.href;
  const linkedInShareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`;

  return <div className="min-h-screen bg-background text-foreground"><ArticleReadingProgress /><main>
    <section className="relative overflow-hidden border-b border-border/70 bg-secondary/30"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_5%,oklch(0.75_0.14_210_/_0.18),transparent_28rem)]" /><div className="container relative py-14 md:py-20"><button onClick={() => setLocation("/blog")} className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-accent"><ArrowLeft className="h-4 w-4" /> All articles</button><div className="mt-10 max-w-4xl"><div className="flex flex-wrap items-center gap-3 font-mono text-[11px] uppercase tracking-[.14em] text-accent"><span>{post.kind}</span><span className="text-muted-foreground">{post.date}</span><span className="inline-flex items-center gap-1 text-muted-foreground"><Clock3 className="h-3.5 w-3.5" /> {post.readingTime}</span></div><h1 className="mt-5 text-4xl leading-[1.08] md:text-6xl">{post.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{post.excerpt}</p><a href={blogAuthorPath(post.author)} className="mt-5 inline-flex text-sm font-semibold text-primary hover:text-accent">By {post.author}</a><div className="mt-6 flex flex-wrap items-center gap-2">{post.categories.map(category => <BlogTopicTagRssAction key={category} topic={category} category />)}{post.tags.map(tag => <BlogTopicTagRssAction key={tag} topic={tag} />)}</div></div></div></section>
    <article className="container grid gap-10 py-14 md:grid-cols-[minmax(0,1fr)_16rem] md:py-20"><div className="max-w-3xl">{post.sections.map(section => <section key={section.heading} className="mb-11"><h2 className="text-2xl md:text-3xl">{section.heading}</h2>{section.paragraphs.map(paragraph => <div key={paragraph} className="prose prose-base mt-5 max-w-none leading-8 prose-invert prose-p:text-muted-foreground prose-strong:text-foreground prose-img:rounded-2xl prose-img:border prose-img:border-border"><Streamdown>{paragraph}</Streamdown></div>)}</section>)}<div className="rounded-2xl border border-accent/25 bg-accent/7 p-6"><p className="flex items-center gap-2 font-mono text-xs uppercase tracking-[.16em] text-accent"><Sparkles className="h-4 w-4" /> Practical takeaways</p><ul className="mt-5 space-y-3">{post.takeaways.map(takeaway => <li key={takeaway} className="flex gap-3 text-sm leading-6 text-foreground"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-accent" />{takeaway}</li>)}</ul></div></div><aside className="h-fit rounded-xl border border-border/80 bg-card p-5 shadow-sm md:sticky md:top-24"><p className="font-mono text-[11px] uppercase tracking-[.15em] text-accent">Source & conversation</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{post.href ? "This on-site reading note expands on the public reference. Visit the source or discuss the architecture context directly." : "This is an evidence-led, anonymized implementation case study. It does not represent unapproved client outcomes or named engagement results."}</p>{post.href ? <a href={post.href} target="_blank" rel="noopener noreferrer" className="mt-5 flex items-center gap-2 text-sm font-semibold text-primary hover:text-accent"><Linkedin className="h-4 w-4" /> {post.sourceLabel} <ExternalLink className="h-3.5 w-3.5" /></a> : <p className="mt-5 flex items-center gap-2 text-sm font-semibold text-primary"><BookOpenText className="h-4 w-4" /> {post.sourceLabel}</p>}<a href={linkedInShareUrl} target="_blank" rel="noopener noreferrer" className="mt-4 flex items-center gap-2 rounded-lg border border-primary/25 bg-primary/5 px-3.5 py-2.5 text-sm font-semibold text-primary hover:border-primary/50 hover:bg-primary/10"><Share2 className="h-4 w-4" /> Share on LinkedIn</a><a href="/expert" className="mt-3 flex items-center gap-2 rounded-lg bg-primary px-3.5 py-2.5 text-sm font-semibold text-primary-foreground"><CalendarDays className="h-4 w-4" /> Discuss this article</a></aside></article>
    <section className="border-t border-border/70 bg-secondary/30"><div className="container py-14 md:py-18"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[.16em] text-accent">Keep reading</p><h2 className="mt-2 text-2xl md:text-3xl">Related architecture notes</h2></div><button onClick={() => setLocation("/blog")} className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-accent">All articles <ArrowUpRight className="h-4 w-4" /></button></div><div className="mt-7 grid gap-4 md:grid-cols-2">{relatedPosts.map(related => <article key={related.slug} className="rounded-xl border border-border/80 bg-card p-5 shadow-sm"><div className="flex items-center justify-between gap-3 font-mono text-[10px] uppercase tracking-wide text-accent"><a href={blogTopicPath(related.category)}>{related.category}</a><span className="text-muted-foreground">{related.readingTime}</span></div><h3 className="mt-5 text-xl leading-7">{related.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{related.excerpt}</p><button onClick={() => setLocation(`/blog/${related.slug}`)} className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-accent">Read related note <ArrowUpRight className="h-4 w-4" /></button></article>)}</div></div></section>
    <section className="border-t border-border/70"><div className="container py-14 md:py-18"><p className="flex items-center gap-2 font-mono text-xs uppercase tracking-[.16em] text-accent"><Tag className="h-4 w-4" /> Topic recommendations</p><div className="mt-3 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl md:text-3xl">Continue through related identity topics.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Move from this article into adjacent topics with additional architecture and implementation context.</p></div><a href={blogAuthorPath(post.author)} className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary">More from {post.author.split(" ")[0]} <ArrowUpRight className="h-4 w-4" /></a></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTopics.map(({ topic, count }) => <a key={topic} href={blogTopicPath(topic)} className="rounded-2xl border border-border/80 bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-accent/55"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-accent">Related topic</p><h3 className="mt-3 text-lg">{topic}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{count} {count === 1 ? "related article" : "related articles"} available in the library.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">Explore topic <ArrowUpRight className="h-3.5 w-3.5" /></span></a>)}</div></div></section>
  </main></div>;
}
