import { ArrowUpRight, FileLock2, LockKeyhole, LogIn, ShieldAlert } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import PublicSiteHeader from "@/components/PublicSiteHeader";
import { trpc } from "@/lib/trpc";

export default function ClientResources() {
  const { loading, user } = useAuth();
  const isClient = user?.role === "client" || user?.role === "admin";
  const resources = trpc.clientResources.list.useQuery(undefined, { enabled: isClient, refetchOnWindowFocus: false });

  return <div className="min-h-screen bg-[#060b18] text-slate-100"><PublicSiteHeader currentPath="/post-call-resources" /><main className="container py-12 sm:py-18">{loading ? <AccessState title="Checking protected access…" body="Loading the approved engagement resource library." /> : !user ? <AccessState icon={<LockKeyhole className="mx-auto h-9 w-9 text-cyan-300" />} title="Client access required" body="Sign in with the account approved for this engagement to access protected materials." action={<button onClick={() => startLogin()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#4f89d9] px-4 py-3 text-sm font-bold text-white"><LogIn className="h-4 w-4" /> Sign in</button>} /> : !isClient ? <AccessState icon={<ShieldAlert className="mx-auto h-9 w-9 text-amber-300" />} title="Resource access pending" body="This library is restricted to approved client and project-owner accounts. Contact your engagement lead if you need access." /> : <><section className="max-w-3xl"><p className="flex items-center gap-2 font-mono text-[11px] font-semibold uppercase tracking-[.16em] text-cyan-300"><FileLock2 className="h-4 w-4" /> Approved engagement materials</p><h1 className="mt-5 text-4xl font-extrabold tracking-[-.055em] text-white sm:text-6xl">Protected planning context.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300">These resources support agreed engagement work. They contain safe planning structures rather than credentials, data extracts, or system secrets.</p></section><section className="mt-11 grid gap-5 lg:grid-cols-3">{resources.isLoading ? Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-72 animate-pulse rounded-[1.6rem] border border-white/8 bg-white/[.035]" />) : resources.data?.map(resource => <article key={resource.id} className="flex flex-col rounded-[1.6rem] border border-white/9 bg-[linear-gradient(145deg,rgba(21,33,59,.88),rgba(9,17,34,.88))] p-6 shadow-[0_24px_70px_-48px_rgba(35,146,225,.7)] transition duration-200 hover:-translate-y-1 hover:border-cyan-300/30"><p className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-cyan-300">{resource.category}</p><h2 className="mt-3 text-xl font-bold tracking-[-.035em] text-white">{resource.title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{resource.summary}</p><div className="mt-6 border-t border-white/8 pt-5"><p className="text-[11px] font-semibold uppercase tracking-[.11em] text-slate-500">Included prompts</p><ul className="mt-3 space-y-2">{resource.sections.map(section => <li key={section} className="flex items-center gap-2 text-sm text-slate-300"><ArrowUpRight className="h-3.5 w-3.5 text-cyan-300" />{section}</li>)}</ul></div></article>)}</section></>}</main></div>;
}

function AccessState({ icon, title, body, action }: { icon?: React.ReactNode; title: string; body: string; action?: React.ReactNode }) {
  return <section className="mx-auto grid min-h-[55vh] max-w-lg place-items-center text-center"><div>{icon}<h1 className="mt-5 text-3xl font-extrabold text-white">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-400">{body}</p>{action}</div></section>;
}
