import { Clock3, Eye, FileWarning, KeyRound, LockKeyhole } from "lucide-react";
import { useState } from "react";
import { Streamdown } from "streamdown";
import { useRoute } from "wouter";
import BrandLockup from "@/components/BrandLockup";
import { articleBodyToMarkdown, type EditableBlogArticle } from "@/lib/blogContentEditor";
import type { EditableUseCase } from "@/lib/adminContentEditors";
import { trpc } from "@/lib/trpc";

function Unavailable() { return <main className="container grid min-h-screen place-items-center py-16 text-center"><div><FileWarning className="mx-auto h-9 w-9 text-amber-300" /><h1 className="mt-5 text-3xl font-extrabold text-white">Draft preview unavailable</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">This private preview link has expired, been revoked, or is invalid. Ask the content owner for a new link.</p></div></main>; }

export default function DraftPreview() {
  const [, params] = useRoute("/draft-preview/:token");
  const token = params?.token ?? "";
  const [password, setPassword] = useState("");
  const [submittedPassword, setSubmittedPassword] = useState<string | undefined>();
  const preview = trpc.siteContent.draftPreview.useQuery({ token, password: submittedPassword }, { enabled: /^[a-f0-9]{32}$/.test(token), retry: false });
  if (preview.isLoading) return <div className="min-h-screen bg-[#060b18] text-slate-100"><main className="container grid min-h-screen place-items-center text-sm text-slate-400">Loading private draft preview…</main></div>;
  const passwordChallenge = Boolean(preview.data?.passwordRequired || (submittedPassword && preview.error));
  if (passwordChallenge) return <div className="min-h-screen bg-[#060b18] text-slate-100"><header className="border-b border-white/8 bg-[#07101e]/86"><div className="container py-3"><BrandLockup size={34} /></div></header><main className="container grid min-h-[76vh] place-items-center py-16"><form onSubmit={(event) => { event.preventDefault(); setSubmittedPassword(password); }} className="w-full max-w-md rounded-[1.75rem] border border-white/10 bg-white/[.035] p-7"><KeyRound className="h-7 w-7 text-cyan-300" /><h1 className="mt-5 text-2xl font-extrabold text-white">Protected draft preview</h1><p className="mt-3 text-sm leading-6 text-slate-400">Enter the review password shared by the content owner.{preview.data?.expiresAt ? ` This link expires ${new Date(preview.data.expiresAt).toLocaleString()}.` : ""}</p><label className="mt-6 grid gap-2 text-xs font-semibold text-slate-300">Preview password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoFocus className="rounded-lg border border-white/10 bg-[#050a14] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300" /></label>{preview.error && <p className="mt-3 text-xs text-rose-200">The preview password is not valid.</p>}<button type="submit" className="mt-5 w-full rounded-lg bg-cyan-300 px-4 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-200">Open draft preview</button></form></main></div>;
  if (!preview.data) return <div className="min-h-screen bg-[#060b18] text-slate-100"><Unavailable /></div>;
  const unlockedPreview = preview.data as { passwordRequired: false; area: "blog" | "use-cases"; entryKey: string; document: string; expiresAt: Date };
  const item = JSON.parse(unlockedPreview.document) as EditableBlogArticle | EditableUseCase;
  const isBlog = unlockedPreview.area === "blog";
  return <div className="min-h-screen bg-[#060b18] text-slate-100"><header className="border-b border-white/8 bg-[#07101e]/86"><div className="container flex flex-wrap items-center justify-between gap-4 py-3"><BrandLockup size={34} /><p className="flex items-center gap-2 rounded-full border border-amber-300/25 bg-amber-300/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.14em] text-amber-100"><LockKeyhole className="h-3.5 w-3.5" /> Private draft preview</p></div></header><main className="container py-12 sm:py-16"><section className="max-w-4xl"><p className="flex items-center gap-2 font-mono text-[11px] uppercase tracking-[.16em] text-cyan-300"><Eye className="h-4 w-4" /> Unpublished review copy</p><h1 className="mt-5 text-4xl font-extrabold tracking-[-.055em] text-white sm:text-6xl">{item.title}</h1><p className="mt-5 flex items-center gap-2 text-sm text-slate-400"><Clock3 className="h-4 w-4 text-cyan-300" /> Link expires {new Date(unlockedPreview.expiresAt).toLocaleString()}</p></section>{isBlog ? <article className="prose prose-lg mt-12 max-w-3xl prose-invert prose-headings:text-white prose-p:text-slate-300 prose-strong:text-cyan-100 prose-img:rounded-2xl"><Streamdown>{articleBodyToMarkdown(item as EditableBlogArticle)}</Streamdown></article> : <article className="mt-12 max-w-3xl rounded-[1.75rem] border border-white/9 bg-[linear-gradient(145deg,rgba(21,33,59,.9),rgba(9,17,34,.9))] p-6 sm:p-8"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-cyan-300/25 bg-cyan-300/10 px-2.5 py-1 font-mono text-[10px] text-cyan-100">{(item as EditableUseCase).category}</span><span className="rounded-full border border-white/10 px-2.5 py-1 font-mono text-[10px] text-slate-300">{(item as EditableUseCase).complexity}</span></div><p className="mt-6 text-base leading-8 text-slate-300">{(item as EditableUseCase).businessRequirement}</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><section><h2 className="font-mono text-xs uppercase tracking-[.15em] text-cyan-200">Technical requirements</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{(item as EditableUseCase).technicalSpecifications.map((value) => <li key={value}>• {value}</li>)}</ul></section><section><h2 className="font-mono text-xs uppercase tracking-[.15em] text-cyan-200">Implementation steps</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{(item as EditableUseCase).implementationSteps.map((value, index) => <li key={value}><span className="mr-2 text-cyan-300">{String(index + 1).padStart(2, "0")}</span>{value}</li>)}</ol></section></div></article>}</main></div>;
}
