import { useLocation, useParams } from "wouter";
import { ArrowLeft, ArrowRight, Bookmark, BookmarkCheck, Check, CheckCircle2, ClipboardCheck, Copy, GitPullRequest, Layers3, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useCases30 as useCases, categories, complexityLevels } from "@/lib/useCases30";
import IdentityMark from "@/components/IdentityMark";
import BrandLockup from "@/components/BrandLockup";
import ThemeToggle from "@/components/ThemeToggle";
import { useSavedUseCases } from "@/hooks/useSavedUseCases";

const deliveryLens = [
  { title: "Discover", detail: "Confirm owner, policy scope, source data, target systems, and measurable business outcome." },
  { title: "Design", detail: "Map IdentityIQ objects, configuration dependencies, approval routes, and exception handling." },
  { title: "Build", detail: "Implement in a versioned branch with reusable naming standards and configuration templates." },
  { title: "Validate", detail: "Test normal, failure, exception, and deprovisioning paths using controlled test identities." },
  { title: "Operate", detail: "Assign monitoring, evidence retention, ownership review, and a safe rollback path." },
];

function ComplexityMeter({ level }: { level: string }) {
  const activeCount = level === "Advanced" ? 3 : level === "Intermediate" ? 2 : 1;
  const tone = level === "Advanced" ? "bg-rose-400" : level === "Intermediate" ? "bg-amber-300" : "bg-emerald-400";
  return <span className="inline-flex items-center gap-1.5"><span className="font-mono text-[10px] uppercase tracking-wide text-muted-foreground">{level}</span>{[1, 2, 3].map((dot) => <span key={dot} className={`h-1.5 w-1.5 rounded-full ${dot <= activeCount ? tone : "bg-muted"}`} />)}</span>;
}

export default function UseCaseDetail() {
  const { id } = useParams<{ id: string }>();
  const [, setLocation] = useLocation();
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const { isSaved, toggleSaved } = useSavedUseCases();
  const useCase = useCases.find((item) => item.id === Number(id));

  if (!useCase) return <div className="min-h-screen bg-background grid place-items-center px-6 text-center"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-accent">404 · reference unavailable</p><h1 className="mt-4 text-3xl">Use case not found</h1><Button onClick={() => setLocation("/use-cases")} className="mt-6">Back to use cases</Button></div></div>;

  const category = categories.find((item) => item.id === useCase.category);
  const complexity = complexityLevels.find((item) => item.id === useCase.complexity);
  const handleCopy = (text: string, index: number) => { navigator.clipboard.writeText(text); setCopiedIndex(index); setTimeout(() => setCopiedIndex(null), 1600); };

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-40 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="container flex items-center justify-between gap-4 py-3.5 max-[560px]:flex-col max-[560px]:items-start"><button onClick={() => setLocation("/use-cases")} className="text-left" aria-label="Back to use cases"><BrandLockup markClassName="rounded-xl border border-accent/30 bg-card p-1 shadow-[0_0_28px_-10px_oklch(0.65_0.15_200)]" /></button><div className="flex items-center gap-2 max-[560px]:self-end"><ThemeToggle className="hidden sm:inline-flex" /><Button onClick={() => setLocation("/use-cases")} variant="ghost" size="sm" className="gap-2 text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Catalog</Button><Button onClick={() => toggleSaved(useCase.id)} variant="outline" size="sm" className={`gap-2 border-border/80 bg-card/30 ${isSaved(useCase.id) ? "border-accent/40 text-accent" : "text-muted-foreground hover:text-foreground"}`}>{isSaved(useCase.id) ? <BookmarkCheck className="h-4 w-4" /> : <Bookmark className="h-4 w-4" />}<span className="hidden sm:inline">{isSaved(useCase.id) ? "Saved" : "Save"}</span></Button><button onClick={() => setLocation("/delivery-guide")} className="hidden items-center gap-2 text-sm text-muted-foreground hover:text-accent sm:flex"><GitPullRequest className="h-4 w-4 text-accent" /> CI/CD playbook</button></div></div></header>
      <main>
        <section className="relative overflow-hidden border-b border-border/60"><div className="absolute inset-0 opacity-50 [background-image:radial-gradient(oklch(0.65_0.15_200_/_0.16)_1px,transparent_1px)] [background-size:24px_24px]" /><div className="absolute right-[12%] top-8 text-accent/15"><IdentityMark size={180} /></div><div className="container relative py-12 md:py-16"><div className="flex flex-wrap items-center gap-2"><Badge className={`${category?.color ?? "bg-slate-600"} border-0 text-white`}>{category?.label}</Badge><span className="rounded-full border border-border/70 bg-card/60 px-2.5 py-1"><ComplexityMeter level={complexity?.label ?? useCase.complexity} /></span><span className="flex items-center gap-1.5 font-mono text-xs text-muted-foreground"><IdentityMark className="text-accent/65" size={15} /> UC-{String(useCase.id).padStart(2, "0")}</span></div><h1 className="mt-6 max-w-4xl text-3xl leading-tight md:text-5xl">{useCase.title}</h1><p className="mt-6 max-w-3xl text-base leading-8 text-muted-foreground">{useCase.businessRequirement}</p></div></section>
        <section className="container py-10 md:py-14"><div className="grid gap-8 lg:grid-cols-[1fr_18rem]">
          <div className="space-y-7">
            <Card className="border-border/75 bg-card/55"><CardHeader className="flex-row gap-3 space-y-0"><div className="grid h-10 w-10 place-items-center rounded-lg bg-accent/15 text-accent"><Layers3 className="h-5 w-5" /></div><div><CardTitle className="text-xl">Technical design surface</CardTitle><CardDescription className="mt-1">Components and controls that shape the implementation.</CardDescription></div></CardHeader><CardContent className="space-y-3">{useCase.technicalSpecifications.map((spec, index) => <div key={spec} className="group flex gap-3 rounded-lg border border-border/65 bg-background/35 p-4 transition hover:border-accent/35"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-accent" /><p className="flex-1 text-sm leading-6 text-muted-foreground">{spec}</p><button onClick={() => handleCopy(spec, index)} className="grid h-8 w-8 shrink-0 place-items-center rounded-md text-muted-foreground opacity-0 transition hover:bg-muted hover:text-foreground group-hover:opacity-100" title="Copy specification">{copiedIndex === index ? <Check className="h-4 w-4 text-accent" /> : <Copy className="h-4 w-4" />}</button></div>)}</CardContent></Card>

            <Card className="border-border/75 bg-card/55"><CardHeader><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-primary/35 text-accent"><ClipboardCheck className="h-5 w-5" /></div><div><CardTitle className="text-xl">Implementation blueprint</CardTitle><CardDescription className="mt-1">Use this sequence to turn the pattern into a testable configuration change.</CardDescription></div></div></CardHeader><CardContent><div className="relative space-y-0 before:absolute before:left-4 before:top-5 before:h-[calc(100%-2.5rem)] before:w-px before:bg-border">{useCase.implementationSteps.map((step, index) => <div key={step} className="relative grid grid-cols-[2rem_1fr] gap-4 pb-6 last:pb-0"><div className="z-10 grid h-8 w-8 place-items-center rounded-full border border-accent/35 bg-card font-mono text-xs text-accent">{index + 1}</div><div className="pt-1"><p className="text-sm leading-6 text-foreground">{step}</p>{index === 0 && <p className="mt-1 text-xs leading-5 text-muted-foreground">Start with accountable ownership and a baseline of the current state.</p>}</div></div>)}</div></CardContent></Card>

            <Card className="overflow-hidden border-accent/20 bg-gradient-to-br from-accent/10 via-card/40 to-primary/15"><CardHeader><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-accent text-accent-foreground"><ShieldCheck className="h-5 w-5" /></div><div><CardTitle className="text-xl">Definition of done</CardTitle><CardDescription className="mt-1">Minimum evidence to retain before the change is considered complete.</CardDescription></div></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{["Configured objects are versioned and traceable to an approved change.", "Happy-path, policy-failure, and lifecycle scenarios are tested in a controlled environment.", "Owners and operations teams can explain schedules, alerts, and exception handling.", "Release evidence includes the artifact, approvals, checks, and a rollback-ready path."].map((item) => <div key={item} className="flex gap-3 rounded-lg border border-border/60 bg-background/35 p-4 text-sm leading-6 text-muted-foreground"><Check className="mt-1 h-4 w-4 shrink-0 text-accent" />{item}</div>)}</CardContent></Card>
          </div>
          <aside className="space-y-5 lg:sticky lg:top-22 lg:h-fit"><Card className="border-border/75 bg-card/55"><CardHeader className="flex-row items-center gap-2 space-y-0"><IdentityMark className="text-accent" size={20} /><CardTitle className="text-base">Quick reference</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Category</p><p className="mt-1 flex items-center gap-2 text-sm"><span className={`h-2 w-2 rounded-full ${category?.color ?? "bg-slate-600"}`} />{category?.label}</p></div><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Complexity</p><p className="mt-1"><ComplexityMeter level={useCase.complexity} /></p></div><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Key components</p><p className="mt-1 text-sm">{useCase.technicalSpecifications.length} design elements</p></div><div className="border-t border-border/60 pt-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground">Keywords</p><div className="mt-2 flex flex-wrap gap-1.5">{useCase.keywords.map((keyword) => <span key={keyword} className="rounded-md bg-muted px-2 py-1 text-[10px] text-muted-foreground">{keyword}</span>)}</div></div></CardContent></Card>
            <button onClick={() => setLocation("/delivery-guide")} className="group w-full rounded-xl border border-accent/25 bg-accent/8 p-5 text-left transition hover:border-accent/55 hover:bg-accent/12"><GitPullRequest className="h-5 w-5 text-accent" /><p className="mt-3 text-sm font-semibold">Ship it with control.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Apply source, quality, promotion, and operating gates to this implementation.</p><p className="mt-4 flex items-center gap-1 text-xs font-medium text-accent">Open playbook <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" /></p></button>
            <div className="grid grid-cols-2 gap-2">{useCase.id > 1 && <Button onClick={() => setLocation(`/use-case/${useCase.id - 1}`)} variant="outline" size="sm" className="justify-start border-border/80 bg-card/30">← Previous</Button>}{useCase.id < useCases.length && <Button onClick={() => setLocation(`/use-case/${useCase.id + 1}`)} variant="outline" size="sm" className="justify-end border-border/80 bg-card/30">Next →</Button>}</div>
          </aside>
        </div></section>
        <section className="border-t border-border/60 bg-card/20"><div className="container py-10"><p className="flex items-center gap-2 font-mono text-xs uppercase tracking-[0.2em] text-accent"><IdentityMark size={18} /> Delivery lens</p><h2 className="mt-3 text-2xl">Design each use case for its full operating life.</h2><div className="mt-7 grid gap-3 md:grid-cols-5">{deliveryLens.map((lens, index) => <div key={lens.title} className="relative rounded-lg border border-border/70 bg-background/40 p-4 before:absolute before:top-7 before:right-0 before:hidden before:h-px before:w-3 before:translate-x-full before:bg-accent/35 last:before:hidden md:before:block"><div className="flex items-center justify-between"><p className="font-mono text-xs text-accent">0{index + 1}</p><IdentityMark className="text-accent/35" size={16} /></div><p className="mt-3 font-semibold text-sm">{lens.title}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{lens.detail}</p></div>)}</div></div></section>
      </main>
    </div>
  );
}
