import { Link2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type EntryArea = "blog" | "use-cases";
const expiryOptions = [{ hours: 24, label: "24 hours" }, { hours: 72, label: "3 days" }, { hours: 168, label: "7 days" }, { hours: 336, label: "14 days" }, { hours: 720, label: "30 days" }] as const;

export default function DraftPreviewControls({ area, entryKey, document }: { area: EntryArea; entryKey: string; document: string }) {
  const [expiresInHours, setExpiresInHours] = useState<(typeof expiryOptions)[number]["hours"]>(168);
  const [password, setPassword] = useState("");
  const previews = trpc.siteContent.draftPreviews.list.useQuery({ area, entryKey }, { refetchOnWindowFocus: false });
  const create = trpc.siteContent.draftPreviews.create.useMutation({ onSuccess: async (result) => { const link = `${window.location.origin}/draft-preview/${result.token}`; try { await navigator.clipboard.writeText(link); toast.success("Private draft preview link copied.", { description: password ? "The reviewer password is required to open it." : "No preview password was set." }); } catch { toast.success("Private draft preview created.", { description: link }); } setPassword(""); await previews.refetch(); }, onError: (error) => toast.error("Could not create draft preview.", { description: error.message }) });
  const revoke = trpc.siteContent.draftPreviews.revoke.useMutation({ onSuccess: async () => { await previews.refetch(); toast.success("Draft preview link revoked."); }, onError: (error) => toast.error("Could not revoke draft preview.", { description: error.message }) });
  const createPreview = () => { if (password && password.length < 8) { toast.error("Use at least 8 characters for the reviewer password."); return; } create.mutate({ area, entryKey, document, expiresInHours, password: password || undefined }); };
  const active = previews.data?.filter((preview) => !preview.revokedAt && new Date(preview.expiresAt) > new Date()) ?? [];
  return <section className="rounded-xl border border-cyan-300/16 bg-cyan-300/[.035] p-4"><div className="flex items-center gap-2"><Link2 className="h-4 w-4 text-cyan-300" /><h3 className="text-sm font-bold text-cyan-100">Private draft preview</h3></div><p className="mt-1 text-xs leading-5 text-slate-400">Create an opaque review link. It is private by link, expires automatically, and may also require a password.</p><div className="mt-4 grid gap-3 sm:grid-cols-[auto_minmax(0,1fr)_auto]"><label className="grid gap-1 text-[11px] font-semibold text-slate-300">Expires after<select value={expiresInHours} onChange={(event) => setExpiresInHours(Number(event.target.value) as (typeof expiryOptions)[number]["hours"])} className="rounded-lg border border-white/10 bg-[#050a14] px-2.5 py-2 text-xs text-white outline-none focus:border-cyan-300">{expiryOptions.map((option) => <option key={option.hours} value={option.hours}>{option.label}</option>)}</select></label><label className="grid gap-1 text-[11px] font-semibold text-slate-300">Reviewer password <span className="font-normal text-slate-500">optional, min. 8 characters</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Leave blank for link-only access" className="rounded-lg border border-white/10 bg-[#050a14] px-2.5 py-2 text-xs text-white outline-none placeholder:text-slate-600 focus:border-cyan-300" /></label><button type="button" onClick={createPreview} disabled={create.isPending} className="self-end inline-flex items-center justify-center gap-2 rounded-lg border border-cyan-300/30 px-3 py-2 text-xs font-bold text-cyan-100 hover:bg-cyan-300/10 disabled:opacity-50"><ShieldCheck className="h-3.5 w-3.5" /> {create.isPending ? "Creating…" : "Copy review link"}</button></div>{active.length ? <div className="mt-4 space-y-2 border-t border-white/8 pt-3">{active.map((preview) => <div key={preview.id} className="flex flex-wrap items-center justify-between gap-2 text-xs"><span className="flex items-center gap-1.5 text-slate-400">{preview.passwordHash && <LockKeyhole className="h-3.5 w-3.5 text-cyan-300" />} Expires {new Date(preview.expiresAt).toLocaleString()}</span><button type="button" onClick={() => revoke.mutate({ id: preview.id })} disabled={revoke.isPending} className="font-semibold text-rose-200 hover:text-rose-100">Revoke link</button></div>)}</div> : null}</section>;
}
