import { ArrowUpRight, Clock3, Landmark, Tags } from "lucide-react";
import { useMemo } from "react";
import { useLocation } from "wouter";
import { legacyKnowledgeArticles, legacyKnowledgePublishedAt, legacyKnowledgeTopics } from "@/lib/legacyKnowledge";

export default function FeaturedKnowledgeInsights() {
  const [, setLocation] = useLocation();
  const insights = useMemo(() => [...legacyKnowledgeArticles].filter(article => legacyKnowledgePublishedAt[article.slug]).sort((first, second) => Date.parse(legacyKnowledgePublishedAt[second.slug]!) - Date.parse(legacyKnowledgePublishedAt[first.slug]!)).slice(0, 3), []);
  return <section className="border-b border-border/70 bg-secondary/30"><div className="container py-12 md:py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 font-mono text-xs uppercase tracking-[.17em] text-accent"><Landmark className="h-4 w-4" /> Selected archive insights</p><h2 className="mt-3 text-3xl md:text-4xl">Technical context worth revisiting.</h2><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">A curated path into the most recently published public knowledge notes, linking directly to focused archive topics for deeper historical implementation context.</p></div><button onClick={() => setLocation("/knowledge")} className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-accent">Browse knowledge archive <ArrowUpRight className="h-4 w-4" /></button></div><div className="mt-7 grid gap-4 lg:grid-cols-3">{insights.map((insight, index) => { const topic = legacyKnowledgeTopics[insight.slug]?.[0]; const publishedAt = legacyKnowledgePublishedAt[insight.slug]!; return <article key={insight.slug} className="group rounded-2xl border border-border/80 bg-card p-5 shadow-[0_18px_45px_-38px_oklch(0.42_0.11_230)] transition hover:-translate-y-1 hover:border-accent/45 hover:shadow-md"><div className="flex items-center justify-between gap-3 font-mono text-[10px] uppercase tracking-wide text-accent"><span>Archive pick · {String(index + 1).padStart(2, "0")}</span><span className="inline-flex items-center gap-1 text-muted-foreground"><Clock3 className="h-3 w-3" /> {new Date(publishedAt).toLocaleDateString("en", { year: "numeric", month: "short" })}</span></div><h3 className="mt-5 text-xl leading-7 group-hover:text-primary">{insight.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{insight.summary}</p><div className="mt-5 flex flex-wrap gap-2">{(legacyKnowledgeTopics[insight.slug] ?? []).slice(0, 2).map(item => <button key={item} onClick={() => setLocation(`/knowledge?topic=${encodeURIComponent(item)}`)} className="inline-flex items-center gap-1 rounded-md bg-primary/8 px-2 py-1 text-[10px] font-semibold text-primary transition hover:bg-primary/14"><Tags className="h-3 w-3" /> {item}</button>)}</div><button onClick={() => setLocation(topic ? `/knowledge?topic=${encodeURIComponent(topic)}` : "/knowledge")} className="mt-6 inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-accent">Open archive context <ArrowUpRight className="h-4 w-4" /></button></article>; })}</div></div></section>;
}
